package top.vuhe.sw.common.util

import org.springframework.data.redis.connection.stream.StreamRecords

/**
 * 默认过期时长，单位：秒
 */
const val DEFAULT_EXPIRE = (60 * 60 * 24).toLong()

/**
 * 不设置过期时长
 */
const val NOT_EXPIRE: Long = -1

/**
 * Stream key
 */
const val STREAM_KEY = "realtime_stream"

fun sendToRedisStream(obj: Any) {
    val info = toJson(obj)
    val record = StreamRecords.newRecord().ofObject(info).withStreamKey(STREAM_KEY)
    val reRecord = beanUtil.streamOperations.add(record)
    utilLog.info("$reRecord : ${reRecord?.timestamp} , ${reRecord?.shouldBeAutoGenerated()}")
}





